import requests  
import datetime
from random import randint
class BotHandler:

    def __init__(self, token):
        self.token = token
        self.api_url = "https://api.telegram.org/bot{}/".format(token)

    def get_updates(self, offset=None, timeout=30):
        method = 'getUpdates'
        params = {'timeout': timeout, 'offset': offset}
        resp = requests.get(self.api_url + method, params)
        result_json = resp.json()['result']
        return result_json

    def send_message(self, chat_id, text):
        params = {'chat_id': chat_id, 'text': text}
        method = 'sendMessage'
        resp = requests.post(self.api_url + method, params)
        return resp
    def send_Sticker(self, chat_id, file_id):
        params = {'chat_id': chat_id, 'file_id': file_id}
        method = 'sendSticker'
        resp = requests.post(self.api_url + method, params)
        return resp
    def get_last_update(self):
        get_result = self.get_updates()

        if len(get_result) > 0:
            last_update = get_result[-1]
        else:
            last_update = get_result[len(get_result)]

        return last_update
ahegao = ['CAACAgIAAxkBAAJyDV_LCT29tnc_BfFldP997-MNC8-FAAMFAAL4fMsRneE1KtqOdPIeBA', 'CAACAgIAAxkBAAJyEF_LCUjhkWzuisTHK89vktBIAc3hAAIBBQAC-HzLERBxLKAg9aUaHgQ', 'CAACAgIAAxkBAAJyE1_LCauLy809KI-aaJkN7pOJfWaYAAICBQAC-HzLEcJkE--nF6SNHgQ', 'CAACAgIAAxkBAAJyFl_LCcV30CGgwtbgIvmizv9rTQyDAAIDBQAC-HzLEdg7iZ3IYlhNHgQ', 'CAACAgIAAxkBAAJyGV_LCdKfLPT8vCKKLHTq_q4EgQkqAAIEBQAC-HzLEWLrGhl-DlgFHgQ', 'CAACAgIAAxkBAAJyHF_LCd2kolHLmfUQ4cV9_VGED12IAAIFBQAC-HzLEZM98CMt8ZZ1HgQ', 'CAACAgIAAxkBAAJyH1_LCel60gnLMBage9jHYEKLkJHwAAIGBQAC-HzLEeMaXsya0LepHgQ', 'CAACAgIAAxkBAAJyIl_LCfiR56Onp6u0CrPhWrxA1ZSMAAIHBQAC-HzLEbAoFdT3QTUqHgQ', 'CAACAgIAAxkBAAJyJV_LCgJbNzPFYTB7ijaaDfdpiYS9AAIIBQAC-HzLEVUS1tc2H0HOHgQ', 'CAACAgIAAxkBAAJyKF_LCg9sx6JiTtGwDBhkz4WU4oLoAAIJBQAC-HzLEfk36b7s4WvyHgQ', 'CAACAgIAAxkBAAJyK1_LChqH3PVbK9YKbtfEJnmDuzjSAAIKBQAC-HzLEXhi2cxaddjfHgQ', 'CAACAgIAAxkBAAJyLl_LCijJVV_2d94yE0wbCbqLhHvIAAINBQAC-HzLETWGuDci44SiHgQ', 'CAACAgIAAxkBAAJyMV_LCjFO9uyr872G9hPKQZlAJR4JAAIOBQAC-HzLEe_oBfE4yXqUHgQ', 'CAACAgIAAxkBAAJyNF_LCjwRs5WhG3pCOOBPvxwXvcymAAIPBQAC-HzLET6SCArcNHLOHgQ', 'CAACAgIAAxkBAAJyN1_LCkpvxg4xwA4c4aTDpiLCHiUkAAIQBQAC-HzLEWFVq1zepLbsHgQ', 'CAACAgIAAxkBAAJyOl_LClRK9iZPEoT88T6WbSHbc9ArAAIRBQAC-HzLESySGcrplF2iHgQ', 'CAACAgIAAxkBAAJyPV_LCmQZSzzim5K29hv-sixOygnrAAISBQAC-HzLEekLVCy-RX0eHgQ', 'CAACAgIAAxkBAAJyQF_LCoELze70N81fKIcEzcr-NX-yAAITBQAC-HzLEb1AWA5RbLCDHgQ', 'CAACAgIAAxkBAAJyQ1_LCozWjk7VniNB_JNyBZEdS2LPAAIUBQAC-HzLER-nRP9me7-THgQ', 'CAACAgIAAxkBAAJyRl_LCpuHXcnNwJlywdsdm8N2dDMZAAIVBQAC-HzLEXdVWGbZ1dyzHgQ', 'CAACAgIAAxkBAAJySV_LCqiCPdLkSC9wZD2DuUFMV7a-AAIWBQAC-HzLEb0AAf7Rmg8NER4E', 'CAACAgIAAxkBAAJyTF_LCrUlWv41OYWAZHejcCxZ5XGZAAIXBQAC-HzLEU5suYy3zDALHgQ', 'CAACAgIAAxkBAAJyT1_LCtsgCwpLTxvAK0NVVXfknCllAAIYBQAC-HzLEWFh7t2RkXXLHgQ', 'CAACAgIAAxkBAAJyWF_LCwe_6HLv1LrLiuWeXvmmdUl2AAIaBQAC-HzLEf1T8ANZtL2AHgQ', 'CAACAgIAAxkBAAJyW1_LCxHzwdSgbc4ColTVaxxwheeKAAIbBQAC-HzLETbYUGCOgKghHgQ', 'CAACAgIAAxkBAAJyXl_LCxwnTIeh8ONnTkyBRzHb3jWwAAIcBQAC-HzLEet7ZerQKtZrHgQ', 'CAACAgIAAxkBAAJyYV_LCymgcUx0833rNdxL5J0YyxGyAAIdBQAC-HzLEeTtiGVF7UHyHgQ', 'CAACAgIAAxkBAAJyZF_LCzVjHUujpRDkJ5LVOj5pRnM2AAIeBQAC-HzLESBLP4iZ9tgpHgQ', 'CAACAgIAAxkBAAJyZ1_LCz8nV-mS8r7l7XBXVqKMibzPAAIfBQAC-HzLERaQumGaV34iHgQ', 'CAACAgIAAxkBAAJyal_LC0xxlA0hal7-Ncyn8-CSA63DAAIgBQAC-HzLER8B9WpCYEJpHgQ', 'CAACAgIAAxkBAAJybV_LC1YpgNckjPuFVqulk_Kh3IiKAAIiBQAC-HzLEUaBX7MAAZnPfh4E', 'CAACAgIAAxkBAAJycF_LC1_L0V_Qmz9QkvcYTCX4bB8jAAIkBQAC-HzLEShtA25AhCMSHgQ', 'CAACAgIAAxkBAAJyc1_LC2pD6T8t0uED-GMzwolAlw6TAAIlBQAC-HzLEWPDiuoKGex-HgQ', 'CAACAgIAAxkBAAJydl_LC3YiOmSfw8ry8DB331rWMN5dAAInBQAC-HzLEagQlp09HlIcHgQ', 'CAACAgIAAxkBAAJyeV_LC4E0EdRIOTvt9hiYu9HNbZpNAAIoBQAC-HzLEdmC9nGzkkMdHgQ', 'CAACAgIAAxkBAAJyfF_LC40_6NglIpXIzhCnFw5Y315NAAIpBQAC-HzLERFLnymNfcCSHgQ', 'CAACAgIAAxkBAAJyf1_LC5axBFRK5aRjQlWKoURenVxSAAIqBQAC-HzLEWhf7GuQxz37HgQ', 'CAACAgIAAxkBAAJygl_LC6Gppv5AVNouFYYl25NQbENDAAIrBQAC-HzLEUbLXGZjqza5HgQ', 'CAACAgIAAxkBAAJyhV_LC6r5N2yEfM7rzveZOt18pWASAAIsBQAC-HzLEQovFshsKqlTHgQ', 'CAACAgIAAxkBAAJyiF_LC-8rKTkMeukrSUsU3IkXs5RwAAJEAAN_9DMcSy13igSLjkUeBA', 'CAACAgIAAxkBAAJyi1_LDAbmaoYH9ECHEeed1dkZn6SWAAI-AAN_9DMcGcqjEdNr8GweBA', 'CAACAgIAAxkBAAJyjl_LDBPmZ-mRl_oGriS6Cj3YEHvVAAIwAAN_9DMcyORCcJnNisYeBA', 'CAACAgIAAxkBAAJykV_LDCeUmv9OjDqdmjou0vjc8gmOAAI_AAN_9DMc--vvV_O5HlQeBA', 'CAACAgIAAxkBAAJylF_LDDL-4t-Nv5JMnQf7Lo9E2AW3AAIjAAN_9DMc5NXlpJ8ahG4eBA', 'CAACAgIAAxkBAAJyl1_LDFX-BBZ8PLKjwR0M9JFjj0uyAAIlAAN_9DMcg2U0PSsakS8eBA', 'CAACAgIAAxkBAAJyml_LDGjWxoaBwMvBM2cUJ6fxu7DLAAI6AAN_9DMcm8ai4AL6V5IeBA', 'CAACAgIAAxkBAAJynV_LDHKm5CdXpr486lSuk7L7NYbmAAImAAN_9DMcWSveHg8ey8MeBA', 'CAACAgIAAxkBAAJyoF_LDHyBBgd1iMewt8iUHCEbVNg0AAIoAAN_9DMcRTqKBciNvaceBA', 'CAACAgIAAxkBAAJyo1_LDIc5phnTgRdwgtEQPatgGKR0AAIpAAN_9DMcf1wt7nfVYhkeBA', 'CAACAgIAAxkBAAJypl_LDJQo5gcctBa6HjXiQoXNFKaaAAIqAAN_9DMca7_LSqR9ZTAeBA', 'CAACAgIAAxkBAAJyqV_LDJ03DeL1FIB0xIeVZ6wBHQ_SAAIrAAN_9DMclwKRUeyhIf0eBA', 'CAACAgIAAxkBAAJyrF_LDKwh9fe6-dng5bF0PDQKwBfXAAItAAN_9DMcvYpZ8jHMGaseBA', 'CAACAgIAAxkBAAJyr1_LDL1Nfl-BDcEkqGIMPHBG6BnAAAIvAAN_9DMcbAlHdlVnIzkeBA', 'CAACAgIAAxkBAAJysl_LDMfbkXThYAKXgwnyvCI-XAGSAAIhAAN_9DMcrHqdCmmN4VweBA', 'CAACAgIAAxkBAAJytV_LDNJwNPOVwycYnPhpbxxRpw_RAAI0AAN_9DMcljWa__Fda7keBA', 'CAACAgIAAxkBAAJyu1_LDOIN98gHsSC5WkTB8lClqX1zAAI2AAN_9DMcDklQyAkSZQweBA', 'CAACAgIAAxkBAAJyvl_LDOtncP-XCFJ8xzWw7hSZSy7_AAI3AAN_9DMcM3WH7QtvBfQeBA', 'CAACAgIAAxkBAAJywV_LDQLFoqCd8-wfaMmLvHzH-q81AAI7AAN_9DMcn2J7rBwkG-geBA', 'CAACAgIAAxkBAAJyx1_LDRCZKRIvEwccbWeG9M0D2exsAAJGAAN_9DMcqJCSe6zT2JoeBA', 'CAACAgIAAxkBAAJyyl_LDRy8_6zr8Cf17QxIY48uqnRXAAJOAAN_9DMcQ6rEiE90BWkeBA', 'CAACAgIAAxkBAAJyzV_LDSVqRBmxwSBOOQe7IDKKuo-mAAJQAAN_9DMcHjdAzRculfoeBA', 'CAACAgIAAxkBAAJy0F_LDTKx1FShBLGUdjVcyvIBpS8iAAJDAAN_9DMci26E4IXtnTgeBA', 'CAACAgIAAxkBAAJy01_LDUxFedJaUTiZMRf_eBF-UOHCAAJPAAN_9DMcCWr8DUVkydYeBA', 'CAACAgIAAxkBAAJy1l_LDVZOyA69zhTj5lYqD7iE-lVAAAJNAAN_9DMcrcaOXJmwbyQeBA', 'CAACAgIAAxkBAAJy2V_LDWBWsstS5YvjVcORApUvYmPPAAJMAAN_9DMc5Rkl4Tlf5PceBA', 'CAACAgIAAxkBAAJy3F_LDW0AAbIn5npb1-LEh3dkB1Lj0AACOAADf_QzHMgTQFWy8doRHgQ', 'CAACAgIAAxkBAAJy31_LDXbEfkZClKni4PZ8G4063vAqAAIgAAN_9DMc6cpEePwAAZmtHgQ', 'CAACAgIAAxkBAAJy4l_LDX8FFX0jzRKlu5Gk1XTUDol8AAJCAAN_9DMclrUTrB8DMZMeBA', 'CAACAgIAAxkBAAJy5V_LDYQctshrwBSVsdhMjmAEyrJqAAJAAAN_9DMcag1pqKGdMNAeBA', 'CAACAgIAAxkBAAJy6F_LDY7d5erNOFXQUk0vvGZ7Haj_AAI9AAN_9DMccIlFlKIHF3MeBA', 'CAACAgIAAxkBAAJy61_LDanioQwupj59NMjfb7McU_QuAAIzAAN_9DMcZAHTXoJLpvkeBA', 'CAACAgIAAxkBAAJy7l_LDbmepsGaBITWBPHHfyBSIX52AAIkAAN_9DMcahQvBVUhcOkeBA', 'CAACAgIAAxkBAAJy8V_LDcQGjXnZS09HMMV5M_cpV0eDAAIxAAN_9DMcfZ-PLCY39PseBA', 'CAACAgIAAxkBAAJy91_LDdWu7gx80gzjyVAZEKUMGF_zAAIsAAN_9DMcP7QdXeHdw3geBA', 'CAACAgIAAxkBAAJy-l_LDeQOXx4lCylquvj9wfX9PkUGAAJWAAN_9DMc1nOdnSdbayEeBA', 'CAACAgIAAxkBAAJzA1_LDk1MCmpjAhTr4-G8r3FauvfUAAI5AAN_9DMcwrwa9_1pPloeBA', 'CAACAgIAAxkBAAJzBl_LDlkw8Mlk1WL2LP_bMsCJJEUEAAJVAAN_9DMceeSwltkdfkceBA', 'CAACAgIAAxkBAAJzCV_LDmS11OoSp1hskRAk6SIcshjfAAJXAAN_9DMckniHH-l-f0MeBA', 'CAACAgIAAxkBAAJzDF_LDnJSBWruVlyf0mWbqjE88yE7AAJZAAN_9DMcjvtUjDQJdSceBA', 'CAACAgIAAxkBAAJzD1_LDoMjYopwTOyZSGsVIbgFZB4FAAJaAAN_9DMcKRCo58kV9EEeBA', 'CAACAgIAAxkBAAJzEl_LDoQ8WWg9Yf9nq2dRz39TKxWyAAJiAAN_9DMcfGYhEyvyg3oeBA', 'CAACAgIAAxkBAAJzFV_LDpwlk78mQk1s3z23y2JwCKrOAAJjAAN_9DMcFRwXqDP9udgeBA', 'CAACAgIAAxkBAAJzGF_LDrr-mGvCi7BTWGbnI82XbkjcAAJhAAN_9DMcbhxaptHbglseBA', 'CAACAgIAAxkBAAJzG1_LDsUS4STXaUYY8g4tIVQzzxTfAAJbAAN_9DMcJaxBCSWGcJgeBA', 'CAACAgIAAxkBAAJzHl_LDs_MgZtYjtPVrvPesNOIc9JYAAJcAAN_9DMcWDweMbq8ymQeBA', 'CAACAgIAAxkBAAJzIV_LDtnTUSAz_AABHFdbwpeKqQ_xKwACXwADf_QzHHe3B_EegL-IHgQ', 'CAACAgIAAxkBAAJzJF_LDuJ0pR7HqCmzRZYw5PNoadIpAAJgAAN_9DMcR8qgbcxD_IkeBA', 'CAACAgIAAxkBAAJzJ1_LDwPLQirpkT3WSL6tzkt_vJCQAAJ7AAN_9DMcUPW-OvWmdUUeBA', 'CAACAgIAAxkBAAJzKl_LDw18Pdr8hc4PS6mKvsjj4NmzAAJzAAN_9DMcoXv4RbcAAS8dHgQ', 'CAACAgIAAxkBAAJzLV_LDx0cKywrf4dGmJ1rkiMRorpBAAJ1AAN_9DMcOx3rs2eu6HkeBA', 'CAACAgIAAxkBAAJzMF_LDysW1-HtqxFEK1uh2r6h0NayAAJ2AAN_9DMcGIWsAAF5OX0UHgQ', 'CAACAgIAAxkBAAJzM1_LDzbON65fvZihBa3xZFnbwCWyAAJ5AAN_9DMcqXNriKzIJpgeBA', 'CAACAgIAAxkBAAJzNl_LD0LbTvFJlC6VhQABDHq0iitZfgACdwADf_QzHD0nca9IPwq3HgQ', 'CAACAgIAAxkBAAJzOV_LD0OVXl_IhGXvJdzVrvusAe-9AAJ4AAN_9DMcIiNPDVGn8jEeBA', 'CAACAgIAAxkBAAJzPF_LD1fG3ksQ9pTOrSHmEk6GnNXIAAJ0AAN_9DMceMM7h06M63EeBA', 'CAACAgIAAxkBAAJzP1_LD2_a0RkhPUOeSNzZvWIRfKIeAAJ6AAN_9DMcHbQsK-X1_RAeBA', 'CAACAgIAAxkBAAJzQl_LD4GvZ2mWt70sibQmWfoYsRSqAAJ9AAN_9DMcpCAr3Ctetl0eBA', 'CAACAgIAAxkBAAJzRV_LD42Mk2KK2Z8H7OG2ZIukknOvAAJ-AAN_9DMcIJlxwETPui4eBA', 'CAACAgIAAxkBAAJzSF_LD-cr8b3mrx-Sj8obLHVIhMDbAAJ_AAN_9DMch6Mzgmxe0UseBA', 'CAACAgIAAxkBAAJzS1_LEAABxTWkQte1D0aye4Pz8mL8-AACgAADf_QzHHwC42jxBqInHgQ', 'CAACAgIAAxkBAAJzTl_LEA5SGoYSP4IXtchPN4sDjheuAAKBAAN_9DMcIxiVkkPsIBoeBA', 'CAACAgIAAxkBAAJzUV_LECPBMiAgx2mZ1JEwJn0md7LLAAKCAAN_9DMcHBCPJ-P_RFgeBA', 'CAACAgIAAxkBAAJzVF_LECxrSNsBtptu_7xJMhTpVt4jAAKDAAN_9DMc6yeYldb-kbMeBA', 'CAACAgIAAxkBAAJzV1_LEDYgFCXCnFF9bRIuEZ0cOpmHAAKIAAN_9DMcOnpSz573oUIeBA', 'CAACAgIAAxkBAAJzWl_LEEJ6wygmgiTekraHjiUQGNRIAAKJAAN_9DMc_gU0dKFvAZAeBA', 'CAACAgIAAxkBAAJzXV_LEE0HxtJqwZtqkXoEjV1wEDB7AAKGAAN_9DMc7bTiuR3fgGgeBA', 'CAACAgIAAxkBAAJzYF_LEE58H7C72eU0p47vA9wehUtYAAKEAAN_9DMc4GBymYkDAAFNHgQ', 'CAACAgIAAxkBAAJzY1_LEGXOsvl25eHslpxngK6WYFsjAAKHAAN_9DMcCMrfl3W4MO4eBA', 'CAACAgIAAxkBAAJzZl_LENo3nVIZrJIpn_jhQEwXKvIKAAKKAAN_9DMcbJm000ynQgoeBA', 'CAACAgIAAxkBAAJzaV_LEOoXc_YInIuMrm2NKkdv7PsdAAKLAAN_9DMcvrx9At0pctAeBA', 'CAACAgIAAxkBAAJzbF_LEPMDhyD9-93IGSp8AAEJT2F3UQAChQADf_QzHKcIiswnr8XMHgQ', 'CAACAgIAAxkBAAJzb1_LEQFeNX2VS2C86Fapk4y5JcIhAAKMAAN_9DMcFF271HlPgmseBA', 'CAACAgIAAxkBAAJzcl_LEURqoaAjYWWIyLvi1SHySE5QAAKNAAN_9DMcOCNlZFoI0GoeBA', 'CAACAgIAAxkBAAJzdV_LEU21l3r_yjMxFUpCz1EmIbBbAAKOAAN_9DMck_c9H_K0QMIeBA', 'CAACAgIAAxkBAAJzeF_LEVZbjdILxUBgGjjCL4z2qgGSAAKPAAN_9DMcKnO1vn3N8VUeBA', 'CAACAgIAAxkBAAJze1_LEWXuf2MvC7Oqis1N9bx3GbglAAKQAAN_9DMc9MUUD5O_HYceBA', 'CAACAgIAAxkBAAJzfl_LEXB-Iikomd2lWQl5dhQt8wABuAACkQADf_QzHLcoE_9LNI_bHgQ', 'CAACAgIAAxkBAAJzgV_LEYKf1NYcezSrbRJboYgmm7n0AAKTAAN_9DMc8kcLlhcl-TweBA', 'CAACAgIAAxkBAAJzhF_LEY44nFbIYF_7nwQAAS_RQLcTFgACkgADf_QzHLK02DR0fRigHgQ', 'CAACAgIAAxkBAAJzh1_LEZccsr5OmHkmcM81TArJkU2qAAKVAAN_9DMceN05vEke2BweBA', 'CAACAgIAAxkBAAJzil_LEZ80QUSBg4GAMzC2-o9BHsK0AAKUAAN_9DMcW_KiMn3VsgseBA', 'CAACAgIAAxkBAAJzjV_LEay0Htez8Qqv7LdKUMf8yv7KAAKbAAN_9DMc34nQugPAP9weBA', 'CAACAgIAAxkBAAJzkF_LEcLv3yiPOiYAAdOY68K-YX46TAACogADf_QzHG-ugKt2aM_lHgQ', 'CAACAgIAAxkBAAJzk1_LEcItfoTMcKkpnmZ71VKAZqeZAAKjAAN_9DMcr5YaCEjyQjgeBA', 'CAACAgIAAxkBAAJzll_LEcq_fPFqAvB7YGbNX7aEUTu-AAKkAAN_9DMcGYES-kQe7VEeBA', 'CAACAgIAAxkBAAJzmV_LEis2kHlspYfTyvFgmvsq6CvHAAIBAAM1fnsQ_VPuoG4wEs4eBA', 'CAACAgIAAxkBAAJznF_LEl4t-qG5qrD5krY1ofh7CeQ4AAICAAM1fnsQSXpB7UK6HQEeBA', 'CAACAgIAAxkBAAJzn1_LEmkS7X4a_VZnyIVX9Do-cmiHAAIDAAM1fnsQuHecB_63OGgeBA', 'CAACAgIAAxkBAAJzol_LEnPU5D5XrM3VyvaXKXz64I4NAAIEAAM1fnsQhaGf031p6OkeBA', 'CAACAgIAAxkBAAJzpV_LEn7QsOMCEkneSaFcA-iKMBeUAAIiAAM1fnsQ1IU77jfW87ceBA', 'CAACAgIAAxkBAAJzqF_LEod3B4xsfqgH9WHAqo-zUXRzAAIFAAM1fnsQVUQLDOyVGdseBA', 'CAACAgIAAxkBAAJzq1_LEr2NO8xBvqaMesb-Vuvxk3C9AAIGAAM1fnsQLkYh5myO0ugeBA', 'CAACAgIAAxkBAAJzrl_LEswE2DGbkNguNxCObw08ONCTAAIIAAM1fnsQ76Sfe2Ag2LUeBA', 'CAACAgIAAxkBAAJzsV_LEuVp3Oo5LzVFq41lJrAIjEK6AAIKAAM1fnsQPAjalDeINNoeBA', 'CAACAgIAAxkBAAJztF_LEu94qXzK4BNK8ucgQULh4fIBAAILAAM1fnsQoxj9o9y09xceBA', 'CAACAgIAAxkBAAJzt1_LEvoz4F7CdlDL99IgnowkUw4OAAIMAAM1fnsQWC7DXYyp4wABHgQ', 'CAACAgIAAxkBAAJzul_LEwQseeek93SNMwl7YYQWwnBWAAINAAM1fnsQVC3Afl1N5_4eBA', 'CAACAgIAAxkBAAJzvV_LEw3BojI6Zi8rnkly2X2ONBFnAAIOAAM1fnsQ0cG9hnTcBYAeBA', 'CAACAgIAAxkBAAJzwF_LExP5XqXD5A51tgWvzEzGXyp5AAIPAAM1fnsQeMFhSM6x6bseBA', 'CAACAgIAAxkBAAJzw1_LExnY9fbD7c4FHAeL57fkyvfFAAJIAAM1fnsQ170zBAptFmYeBA', 'CAACAgIAAxkBAAJzxl_LEzQdLW2Imda-A3733oIGrnZPAAIQAAM1fnsQFtAS6QmpLkceBA', 'CAACAgIAAxkBAAJzyV_LE1M732vUMYaVjGbzzMVgmCW8AAIRAAM1fnsQCJ_xQpauzXMeBA', 'CAACAgIAAxkBAAJzzF_LE1w2o18ZY6hknMNAmAYWxFxyAAISAAM1fnsQlVHTRnxauF0eBA', 'CAACAgIAAxkBAAJzz1_LE2SN9D8jbpcMZj8nGx88yWjZAAITAAM1fnsQDXeNVadYKnoeBA', 'CAACAgIAAxkBAAJz0l_LE221xOoCiSqEjFbrjZWTs9hiAAIUAAM1fnsQTYoy-jBZITEeBA', 'CAACAgIAAxkBAAJz1V_LE3Zwk4-Y8jIVoKgu5Y5qzPumAAIXAAM1fnsQp7oqKd87HxYeBA', 'CAACAgIAAxkBAAJz2F_LE4CAn293YHaetQ2Q8en3uK8BAAIYAAM1fnsQeKLZRjXyXlYeBA', 'CAACAgIAAxkBAAJz21_LE4gpMPgxggZv3nMum6H-ybK4AAIZAAM1fnsQTW1ICBgIcnseBA', 'CAACAgIAAxkBAAJz3l_LE5FY4IoyTrg394Own01ewRxiAAIaAAM1fnsQTKwfTGRhVOkeBA', 'CAACAgIAAxkBAAJz4V_LE5oz2LvHFFMcvtsTR8X4wzHSAAIbAAM1fnsQQGrqsXFrZ2EeBA', 'CAACAgIAAxkBAAJz5F_LE6nPtH39Ysz_CpleiYzvQ9rMAAIcAAM1fnsQt8zgqJs_YRseBA', 'CAACAgIAAxkBAAJz51_LE7Otn_sGV_Epfs16hwl1MVj_AAIdAAM1fnsQe_I8BHM60dkeBA', 'CAACAgIAAxkBAAJz6l_LE7snglPpU5S5dQ9gizWkzGsoAAIeAAM1fnsQFofHZkFnthweBA', 'CAACAgIAAxkBAAJz7V_LE8RVhaC0sjHt0sDCxuUwB7dEAAIfAAM1fnsQZDvoo9hwtNMeBA', 'CAACAgIAAxkBAAJz8F_LE84Sqx1MVWuAmKMIw_vWRbxeAAIgAAM1fnsQkf-KiwyBvGQeBA', 'CAACAgIAAxkBAAJz81_LE9sQD5Ut_eIhjWB-GIR2i-U5AAIhAAM1fnsQTlEJtHqjgzoeBA', 'CAACAgIAAxkBAAJz9l_LE-X7WNbaOwvGCffolPtqDhj4AAIjAAM1fnsQoaSaM1PUjSceBA', 'CAACAgIAAxkBAAJz-V_LE--aRU-B3Xwp-4_8XwlOn0nyAAIkAAM1fnsQYBzVEW9UMLgeBA', 'CAACAgIAAxkBAAJz_F_LE_tfgR0KW8EtfA01t2CFnRZXAAImAAM1fnsQ0r-DCipCVFQeBA', 'CAACAgIAAxkBAAJz_1_LFAXFrW4HpUjVzTvdBtx9CTEQAAInAAM1fnsQdBvHdETKl2EeBA', 'CAACAgIAAxkBAAJ0Al_LFA2eVbq8J9KuhAqCwJnr9YMwAAIoAAM1fnsQPI6FuwE-4hseBA', 'CAACAgIAAxkBAAJ0BV_LFBYfJA1tvX36ARekcRa8LKtyAAIpAAM1fnsQ37mRUWSMC8geBA', 'CAACAgIAAxkBAAJ0CF_LFCBqcAuKTpjp49Z9qeA5ePzKAAIqAAM1fnsQVx9tOOMXQaQeBA', 'CAACAgIAAxkBAAJ0C1_LFCznoMzC5YsxbUEE8Ihk5LAfAAIrAAM1fnsQ4FSeshkWoDMeBA', 'CAACAgIAAxkBAAJ0Dl_LFDU-jQ-HwhpbSkLI_tJgvSBOAAItAAM1fnsQgDZdcaI0Mc0eBA', 'CAACAgIAAxkBAAJ0EV_LFD6W2tsYeAh97DW1EyypYgABBwACLgADNX57EAYKYZ226A4tHgQ', 'CAACAgIAAxkBAAJ0FF_LFE9SvGntUqMJSPUkroqFyYMMAAIlAAM1fnsQMAuS_pDXwKAeBA', 'CAACAgIAAxkBAAJ0F1_LFFjy9A-rgc9jay59TTpJX3MPAAIvAAM1fnsQmEzyWjUu5mIeBA', 'CAACAgIAAxkBAAJ0Gl_LFGIOLoSoSU4rNu7IYbwoIX9NAAIwAAM1fnsQecw7TOXa0RIeBA', 'CAACAgIAAxkBAAJ0HV_LFG61sp6Kl0BMQyow2SqGmNClAAIxAAM1fnsQXn-7M1GXFAIeBA', 'CAACAgIAAxkBAAJ0IF_LFHuINNFWpl1UhUowj8uG9EJ7AAIyAAM1fnsQxN1oHZXt_M0eBA', 'CAACAgIAAxkBAAJ0I1_LFIQ8Bt7SopCBky0qfYxUTCNhAAIzAAM1fnsQGOc0Yx-9p50eBA', 'CAACAgIAAxkBAAJ0KV_LFJQjdU72niRJEGyNB0jX969VAAI1AAM1fnsQO6bJiHK0QU4eBA', 'CAACAgIAAxkBAAJ0LF_LFJ_FYZlFRQnJNbKPPK1-fmzcAAI2AAM1fnsQqKvlr1bDL3weBA', 'CAACAgIAAxkBAAJ0L1_LFK-7xORHZ1aZ5j6UF7MwS28iAAI3AAM1fnsQHt_W_KM0DFAeBA', 'CAACAgIAAxkBAAJ0Ml_LFLreWuKqE486pDzDqb9pS4tDAAI4AAM1fnsQElRfibp9VIYeBA', 'CAACAgIAAxkBAAJ0NV_LFMXGDrm-9WYwWAMyc-dbKSrmAAI5AAM1fnsQwi9tMWxUpsQeBA', 'CAACAgIAAxkBAAJ0OF_LFM_fSP7pIHiUcj4YGOdtCYfpAAI6AAM1fnsQJ_K_GLsj0SMeBA', 'CAACAgIAAxkBAAJ0O1_LFN6CkTrMV1KaNLM-U_88r2qnAAI7AAM1fnsQOH9caH1c5E0eBA', 'CAACAgIAAxkBAAJ0Pl_LFOQmSOAjtCh9NXdpX3QK4WTFAAI8AAM1fnsQjaNrCWj4G5EeBA', 'CAACAgIAAxkBAAJ0QV_LFPOOP2CuVN6Ip9llEdJzYzCzAAI9AAM1fnsQsUXFdJxoJFseBA', 'CAACAgIAAxkBAAJ0RF_LFP0hQWsUhSlIxgSiNBjvJaTEAAI-AAM1fnsQ7R8vBocaxo4eBA', 'CAACAgIAAxkBAAJ0TV_LFQ0wgCTjs8cHvOfT7RWrDsMqAAJBAAM1fnsQp8lt0cFvCHweBA', 'CAACAgIAAxkBAAJ0UF_LFRWlwT198P9KZGlQvCBwcHk0AAJCAAM1fnsQH8duZyvsKmoeBA', 'CAACAgIAAxkBAAJ0U1_LFR_uo1SMybgfipUVLYrsXEQ9AAJDAAM1fnsQ0Hf_h4qwAqMeBA', 'CAACAgIAAxkBAAJ0Vl_LFSpmx_B5UOhV27I6JjcaJFIlAAJEAAM1fnsQQTIKOBPtDs8eBA', 'CAACAgIAAxkBAAJ0WV_LFUHzycbXdPGyhdw2NgKqHw_GAAJFAAM1fnsQ3mqUX9Iv4LQeBA', 'CAACAgIAAxkBAAJ0XF_LFUtGZalHhamjHZNYURIRRTRCAAJGAAM1fnsQyG60XZkfUg8eBA', 'CAACAgIAAxkBAAJ0X1_LFVXb9qvkw8h6w52ZBulYMFVUAAJHAAM1fnsQbZbsP8jH5A8eBA', 'CAACAgIAAxkBAAJ0Yl_LFV4gSO9Uxk4GaxtAO1wRpitCAAJJAAM1fnsQmq0juu1yrEoeBA', 'CAACAgIAAxkBAAJ0ZV_LFWiFVKJwlWMcFFV1kxzs3FDQAAJKAAM1fnsQ-U46TmaaP9seBA', 'CAACAgIAAxkBAAJ0aF_LFXCigkzcoFw-XPbHnWk0rZN_AAJLAAM1fnsQXI2AFnqGHGgeBA', 'CAACAgIAAxkBAAJ0a1_LFXyCXP1NtyzMXKiXF4YVFiEtAAJMAAM1fnsQ_HQbT_Q1KhkeBA', 'CAACAgIAAxkBAAJ0bl_LFYT4X00YkLD41qnBBu2FdLcLAAJNAAM1fnsQLAJ9GDXVjEoeBA', 'CAACAgIAAxkBAAJ0cV_LFZJdrO4dUlbBNlTZi9u3by2BAAJOAAM1fnsQwL4Hmoa1lzAeBA', 'CAACAgIAAxkBAAJ0dF_LFZNnJk-e7d-zDBxUrLfU4NxEAAJPAAM1fnsQxmt-wdGb9C0eBA', 'CAACAgIAAxkBAAJ0d1_LFaejaeZz35Ms5eeUCXbLTAmUAAJQAAM1fnsQ8mDRjiNTsQQeBA', 'CAACAgIAAxkBAAJ0el_LFahjLc4GVycWlr_lIHtR2sxfAAJRAAM1fnsQLgxej309_C4eBA', 'CAACAgIAAxkBAAJ0fV_LFci3-HWO0--E7iGgfSUVJW8jAAJSAAM1fnsQuFprJO_-Q0seBA', 'CAACAgIAAxkBAAJ0gF_LFci8HFcSnZOJW5mSzHxFLrqyAAJTAAM1fnsQC-RQ2Yk6lZ0eBA', 'CAACAgIAAxkBAAJ0g1_LFdwPof_mjylDdpH9Rf8a4PCiAAJUAAM1fnsQ-C83EFgrYGkeBA', 'CAACAgIAAxkBAAJ0hl_LFeA0H6M97bRrmpp36C3EOuCeAAJVAAM1fnsQwxhU9ZoFUTUeBA', 'CAACAgIAAxkBAAJ0iV_LFfSJySs253Wm6aWn_UxImi1vAAJWAAM1fnsQjYAILWiXPQceBA', 'CAACAgIAAxkBAAJ0j1_LFfkvnu0ljRSu0ERTf7c_tHv4AAJZAAM1fnsQvcDPRyt4Q7YeBA']
greet_bot = BotHandler("1413022875:AAEIvoqDCwcuHlksHTQVjY7S3NRSqAKRgM0")
commands = ('/help', '/start', '/gun')
guns = ['Винтовки', 'Минигана', 'Автомата', 'Пистолета']
greetings = ('здравствуй', 'привет', 'ку', 'здорово')  
now = datetime.datetime.now()

def pick(words):
    num_words = len(guns)
    num_picked = randint(0, num_words - 1)
    word_picked = words[num_picked]
    return word_picked

def main():  
    new_offset = None
    today = now.day
    hour = now.hour
    while True:
        greet_bot.get_updates(new_offset)
        try:
            last_update = greet_bot.get_last_update()
            last_update_id = last_update['update_id']
            last_chat_text = last_update['message']['text']
            new_offset = last_update_id + 1
            last_chat_id = last_update['message']['chat']['id']
            last_chat_name = last_update['message']['chat']['first_name']
            print(last_chat_name, last_chat_id, last_chat_text)
        except:
            continue
        if last_chat_text.lower() in greetings and today == now.day and 6 <= hour < 12:
            greet_bot.send_message(last_chat_id, 'Доброе утро, {}'.format(last_chat_name))
            today += 1

        elif last_chat_text.lower() in greetings and today == now.day and 12 <= hour < 17:
            greet_bot.send_message(last_chat_id, 'Добрый день, {}'.format(last_chat_name))
            today += 1

        elif last_chat_text.lower() in greetings and today == now.day and 17 <= hour < 23:
            greet_bot.send_message(last_chat_id, 'Добрый вечер, {}'.format(last_chat_name))
            today += 1

        if last_chat_text.lower() in commands:
            if last_chat_text.lower() == '/help':
                greet_bot.send_message(last_chat_id, '/help, /start, /gun, {}'.format(last_chat_name))
            elif last_chat_text.lower() == '/start':
                greet_bot.send_message(last_chat_id, 'Привет! Это мой тестовый бот, который кстати написан на Python 3!')
            elif last_chat_text.lower() == '/gun':
                word = pick(guns)
                greet_bot.send_message(last_chat_id, 'Произведен выстрел из...   {}'.format(word))

        if last_chat_text.lower() == '/ahegao':
            word = pick(ahegao)
            heheh = "https://api.telegram.org/bot1413022875:AAEIvoqDCwcuHlksHTQVjY7S3NRSqAKRgM0/sendSticker?chat_id=" + str(last_chat_id) + '&sticker=' + word
            requests.get(heheh)
        new_offset = last_update_id + 1

if __name__ == '__main__':  
    try:
        main()
    except KeyboardInterrupt:
        exit()
